# Generated by Django 4.2 on 2023-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Weights"),
                            ("S", "Speed"),
                            ("D", "Difficulty"),
                            ("E", "Elevation"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kg", "Kilograms"),
                            ("lbs", "Pounds"),
                            ("mph", "Miles per hour"),
                            ("kph", "Kilometers per hour"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0.0, max_digits=5
                    ),
                ),
            ],
        ),
    ]
