# Generated by Django 4.2 on 2023-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lbs", "Pounds"),
                    ("kg", "Kilograms"),
                    ("kph", "Kilometers per hour"),
                    ("mph", "Miles per hour"),
                ],
                max_length=3,
            ),
        ),
    ]
