# Generated by Django 4.2 on 2023-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("REP", "Reps"),
                            ("CAL", "Calories"),
                            ("DUR", "Duration"),
                            ("DIS", "Distance"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("km", "Kilometers"),
                            ("mi", "Miles"),
                            ("h", "Hours"),
                            ("m", "Minutes"),
                        ],
                        max_length=2,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                (
                    "fields",
                    models.ManyToManyField(related_name="sets", to="fields.field"),
                ),
            ],
        ),
    ]
