# Generated by Django 4.2 on 2023-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sets", "0002_alter_set_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("h", "Hours"),
                    ("m", "Minutes"),
                    ("mi", "Miles"),
                    ("km", "Kilometers"),
                ],
                max_length=2,
            ),
        ),
    ]
