# Generated by Django 4.2 on 2023-04-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sets", "0001_initial"),
        ("records", "0001_initial"),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="type",
        ),
        migrations.AddField(
            model_name="exercise",
            name="records",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="records.record",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="sets",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sets.set",
            ),
        ),
    ]
